class Anime {
  String judul;
  String image;
  String sinopsis;
  double rate;
  int episode;
  String durasi;
  String studio;
  String genre;

  Anime({
    required this.judul,
    required this.image,
    required this.sinopsis,
    required this.rate,
    required this.episode,
    required this.durasi,
    required this.studio,
    required this.genre,
  });
}

List<Anime> listAnime = [
  Anime(
    judul: 'Jujutsu Kaisen',
    image: 'images/jujutsu_kaisen.jpg',
    sinopsis: 'Yuji Itadori, seorang siswa SMA dengan kekuatan fisik luar biasa, terjebak dalam dunia sihir jujutsu setelah menelan Jari Sukuna, artefak terkutuk yang sangat kuat. Bersama teman-temannya di Jujutsu High, ia bertarung melawan roh terkutuk untuk melindungi manusia dari ancaman supernatural. Dengan pertarungan epik, karakter yang kuat, dan animasi luar biasa, Jujutsu Kaisen menjadi salah satu anime terbaik di era modern.',
    rate: 8.6,
    episode: 24,
    durasi: '24 menit',
    studio: 'MAPPA',
    genre: 'Aksi, Supernatural, Dark Fantasy',
  ),
  Anime(
    judul: 'Haikyuu!!',
    image: 'images/haikyuu.jpg',
    sinopsis: 'Shoyo Hinata, seorang siswa pendek yang terinspirasi oleh pemain voli legendaris, bercita-cita menjadi spiker terbaik. Setelah bergabung dengan tim voli SMA Karasuno, ia harus bekerja sama dengan Tobio Kageyama, rivalnya di SMP yang kini menjadi setter tim. Bersama rekan satu timnya, mereka berusaha mengembalikan kejayaan Karasuno di dunia voli. Dengan pertandingan menegangkan, persahabatan yang kuat, dan semangat pantang menyerah, Haikyuu!! menjadi anime olahraga yang penuh inspirasi dan motivasi.',
    rate: 9.0,
    episode: 25,
    durasi: '24 menit',
    studio: 'Production I.G',
    genre: 'Olahraga, Drama, Komedi',
  ),
  Anime(
    judul: 'Moriarty the Patriot',
    image: 'images/moriarty.jpg',
    sinopsis: 'Di Inggris era Victoria, William James Moriarty, seorang bangsawan jenius, bertekad menghancurkan sistem kelas yang korup dengan caranya sendiri. Ia dan saudara-saudaranya merancang kejahatan sempurna untuk menjatuhkan kaum aristokrat yang menindas rakyat jelata. Namun, aksinya menarik perhatian Sherlock Holmes, yang mulai menyelidiki kasus-kasus misterius yang mengarah kepadanya. Moriarty the Patriot menyajikan kisah antihero yang cerdas, penuh intrik, dan pertarungan strategi antara kriminal jenius dan detektif legendaris.',
    rate: 8.2,
    episode: 24,
    durasi: '23 menit',
    studio: 'Production I.G',
    genre: 'Misteri, Kriminal, Sejarah, Thriller',
  ),
  Anime(
    judul: 'Solo Leveling',
    image: 'images/solo_leveling.jpg',
    sinopsis: 'Di dunia di mana gerbang misterius muncul dan menghubungkan dunia manusia dengan monster, Sung Jin-Woo adalah hunter rank E yang dianggap paling lemah. Namun, setelah selamat dari dungeon berbahaya, ia mendapatkan kekuatan misterius yang memungkinkannya untuk "level up" tanpa batas, sesuatu yang tidak dimiliki hunter lain. Dengan kekuatan barunya, ia berusaha menjadi hunter terkuat dan mengungkap rahasia di balik sistem yang mengubah hidupnya. Solo Leveling menghadirkan aksi epik, perkembangan karakter luar biasa, dan pertarungan intens yang membuatnya menjadi salah satu anime paling dinantikan.',
    rate: 8.5,
    episode: 12,
    durasi: '23 menit',
    studio: ' A-1 Pictures',
    genre: 'Aksi, Fantasi, Supernatural',
  ),
  Anime(
    judul: 'The Apothecary Diaries',
    image: 'images/apotechary_dairies.jpg',
    sinopsis: 'Maomao, seorang gadis pintar yang diculik dan dijual sebagai pelayan di istana kekaisaran, menyembunyikan kecerdasannya agar tetap aman. Namun, ketika ia mulai memecahkan misteri penyakit yang menimpa para selir, bakatnya menarik perhatian Jinshi, pejabat tinggi istana yang penuh rahasia. Dengan pengetahuan luas tentang obat-obatan dan racun, Maomao terlibat dalam berbagai intrik istana yang berbahaya. The Apothecary Diaries menyajikan cerita misteri yang cerdas dengan latar sejarah yang memukau.',
    rate: 8.4,
    episode: 24,
    durasi: '23 menit',
    studio: 'MAPPA',
    genre: 'Misteri, Sejarah, Drama',
  ),
  Anime(
    judul: 'Attack on Titan',
    image: 'images/attack_on_titan.jpg',
    sinopsis: 'Dunia manusia terkurung di dalam tembok raksasa untuk melindungi diri dari Titan, makhluk pemakan manusia yang mengancam keberadaan mereka. Eren Yeager, setelah menyaksikan kehancuran akibat Titan, bersumpah untuk membalas dendam dan bergabung dengan Pasukan Pengintai. Namun, seiring berjalannya waktu, ia mulai mengungkap konspirasi besar di balik keberadaan Titan dan sejarah dunia. Attack on Titan menghadirkan kisah penuh aksi, pengkhianatan, dan pertarungan epik yang menjadikannya salah satu anime terbaik sepanjang masa.',
    rate: 9.0,
    episode: 89,
    durasi: '24 menit',
    studio: 'Wit Studio',
    genre: 'Aksi, Fantasi Gelap, Drama, Militer',
  ),
  Anime(
    judul: 'One Piece',
    image: 'images/one_piece.jpg',
    sinopsis: 'Bermimpi menjadi Raja Bajak Laut, Monkey D. Luffy memulai perjalanan mencari One Piece, harta karun legendaris yang ditinggalkan oleh Gol D. Roger. Bersama kru Bajak Laut Topi Jerami, ia menjelajahi lautan Grand Line, menghadapi musuh kuat, menjalin persahabatan, dan mengungkap misteri besar dunia. Dengan aksi seru, humor, serta cerita penuh emosi dan kejutan, One Piece menjadi salah satu anime terpopuler sepanjang masa.',
    rate: 8.7,
    episode: 1100,
    durasi: '24 menit',
    studio: 'Toei Animation',
    genre: 'Petualangan, Aksi, Fantasi',
  ),
  Anime(
    judul: 'Black Butler',
    image: 'images/black_buttler.jpg',
    sinopsis: 'Di era Victoria, Ciel Phantomhive, seorang bangsawan muda, menjadi tangan kanan Ratu dalam mengatasi kejahatan di Inggris. Ia mengikat kontrak dengan Sebastian Michaelis, iblis berbentuk butler yang membantunya membalas dendam terhadap orang-orang yang menghancurkan hidupnya. Dengan plot penuh misteri, elemen supernatural, dan sentuhan komedi gelap, Black Butler menyajikan kisah yang elegan dan menegangkan.',
    rate: 7.8,
    episode: 38,
    durasi: '24 menit',
    studio: 'A-1 Pictures',
    genre: 'Misteri, Supernatural, Drama, Fantasi Gelap',
  ),
  Anime(
    judul: 'Spy x Family',
    image: 'images/spy_familiy.jpg',
    sinopsis: 'Seorang mata-mata terbaik, Loid Forger, ditugaskan untuk menyusup ke sebuah sekolah elit demi menjaga perdamaian antara dua negara. Untuk itu, ia membentuk "keluarga palsu" dengan Yor, seorang pembunuh bayaran, dan Anya, seorang gadis kecil yang bisa membaca pikiran. Tanpa saling mengetahui identitas asli masing-masing, mereka menjalani kehidupan penuh aksi, humor, dan momen keluarga yang menyentuh hati.',
    rate: 8.6,
    episode: 25,
    durasi: '24 menit',
    studio: 'Wit Studio, CloverWorks',
    genre: 'Aksi, Komedi, Slice of Life',
  ),
  Anime(
    judul: 'Blue Lock',
    image: 'images/blue_lock.jpg',
    sinopsis: 'Setelah kekalahan Jepang di Piala Dunia, program Blue Lock dibentuk untuk menciptakan striker terbaik yang bisa membawa negara ke kemenangan. Yoichi Isagi, seorang pemain muda berbakat, harus bersaing dengan ratusan pemain lain dalam sistem eliminasi brutal yang menuntut keegoisan dan insting pembunuh di lapangan. Dengan atmosfer kompetisi yang intens dan aksi sepak bola yang penuh strategi, Blue Lock menjadi anime olahraga yang penuh ketegangan dan adrenalin.',
    rate: 8.3,
    episode: 24,
    durasi: '24 menit',
    studio: '8bit',
    genre: 'Olahraga, Psikologi, Shounen',
  ),
  Anime(
    judul: 'Horimiya',
    image: 'images/horimiya.jpg',
    sinopsis: 'Di sekolah, Hori Kyoko adalah siswi yang populer dan ceria, sedangkan Izumi Miyamura tampak pendiam dan kutu buku. Namun, keduanya ternyata menyimpan sisi lain dari diri mereka. Saat mereka tanpa sengaja mengetahui rahasia masing-masing, hubungan mereka berkembang menjadi lebih dekat. Horimiya adalah anime romansa ringan yang penuh kehangatan, humor, dan kisah cinta remaja yang menyentuh hati.',
    rate: 8.2,
    episode: 13,
    durasi: '24 menit',
    studio: 'CloverWorks',
    genre: 'Romansa, Slice of Life, Komedi, Sekolah',
  ),
  Anime(
    judul: 'Death Note',
    image: 'images/death_note.jpg',
    sinopsis: 'Seorang siswa jenius, Light Yagami, menemukan sebuah buku misterius bernama Death Note, yang bisa membunuh siapa pun hanya dengan menuliskan namanya. Dengan ambisi menciptakan dunia tanpa kejahatan, Light mulai menghapus penjahat dari dunia, namun aksinya menarik perhatian detektif legendaris L. Duel kecerdasan antara Light dan L pun dimulai dalam anime thriller psikologi yang penuh intrik dan ketegangan.',
    rate: 8.6,
    episode: 37,
    durasi: '23 menit',
    studio: 'Madhouse',
    genre: 'Misteri, Supernatural, Psikologi, Thriller',
  ),
  Anime(
    judul: 'Wind Breaker',
    image: 'images/wind_breaker.jpg',
    sinopsis: 'Haruka Sakura, seorang siswa tangguh dengan tekad untuk menjadi yang terkuat, masuk ke Akademi Furin, sekolah yang dipenuhi petarung terbaik. Namun, sekolah ini bukanlah sekadar tempat bagi anak-anak nakal—mereka melindungi kota dari ancaman luar. Dengan pertarungan sengit dan persahabatan yang kuat, Wind Breaker menawarkan kisah aksi seru tentang keberanian dan kekuatan.',
    rate: 7.5,
    episode: 13,
    durasi: '24 menit',
    studio: 'CloverWorks',
    genre: 'Aksi, Sekolah, Delinquent, Shounen',
  ),
  Anime(
    judul: 'Tokyo Ghoul',
    image: 'images/tokyo_ghoul.jpg',
    sinopsis: 'Di dunia di mana Ghoul—makhluk pemakan manusia—bersembunyi di antara manusia, seorang mahasiswa bernama Ken Kaneki mengalami kecelakaan yang mengubahnya menjadi setengah Ghoul. Kini, ia harus bertahan hidup di dunia yang penuh bahaya, belajar mengendalikan kekuatan barunya, dan menemukan identitasnya di antara dua dunia yang bertolak belakang. Dengan aksi brutal dan kisah psikologi mendalam, Tokyo Ghoul adalah anime yang penuh ketegangan dan emosi.',
    rate: 7.8,
    episode: 24,
    durasi: '24 menit',
    studio: 'Pierrot',
    genre: 'Aksi, Horor, Supernatural, Psikologi',
  ),
  Anime(
    judul: 'Hunter x Hunter',
    image: 'images/hunter.jpg',
    sinopsis: 'Gon Freecss, seorang anak berusia 12 tahun, memulai perjalanan untuk menjadi seorang Hunter—petualang elit yang memiliki kemampuan luar biasa. Dalam perjalanannya, ia bertemu Killua, Kurapika, dan Leorio, yang memiliki tujuan masing-masing. Dengan pertarungan seru, strategi cerdas, dan dunia yang luas, Hunter x Hunter adalah salah satu anime petualangan terbaik yang penuh dengan tantangan dan kejutan.',
    rate: 9.0,
    episode: 148,
    durasi: '23 menit',
    studio: 'MAPPA',
    genre: 'Aksi, Petualangan, Fantasi, Shounen',
  ),
];